[package]
name = "sgx_quote_verify"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Intel SGX quote verification"

[lib]
name = "sgx_quote_verify"
crate-type = ["cdylib"]

[dependencies]
intel-tee-quote-verification-rs = "0.2"
