[package]
name = "sgx_quote"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Intel SGX quote parsing"

[lib]
crate-type = ["cdylib"]

[dependencies]
asn1-rs = { version = "0.5", optional = true }
hex = "0.4"
scroll = { version = "0.11", features = ["derive"] }
wasm-bindgen = { version = "0.2", optional = true }
x509-parser = { version = "0.15", optional = true }

[features]
wasm = ["dep:wasm-bindgen", "dep:x509-parser", "dep:asn1-rs"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true
strip = "debuginfo"
