[package]
name = "sgx_quote"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Intel SGX quote parsing"

[lib]
crate-type = ["cdylib"]

[dependencies]
hex = "0.4"
scroll = { version = "0.11", features = ["derive"] }
wasm-bindgen = { version = "0.2", optional = true }

[features]
wasm = ["dep:wasm-bindgen"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

