[package]
name = "sgx_quote"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Intel SGX quote parsing"

[dependencies]
hex = "0.4"
scroll = { version = "0.11", features = ["derive"] }
