[package]
name = "maa_client"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21"
hex = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
jsonwebtoken-rustcrypto = "1.2"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
