[package]
name = "sev_quote"
version = "0.2.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "AMD SEV quote parsing and verification"

[lib]
name = "sev_quote"
crate-type = ["cdylib","rlib"]

[dependencies]
asn1-rs = "0.5"
asn1 = "0.15"
bincode = "1.3"
hex = { workspace = true }
log = { workspace = true }
openssl = { workspace = true }
reqwest = { version = "0.11", features = ["json", "native-tls"] }
sev = { version =  "1.2", features = ["openssl", "sev"] }
thiserror = { workspace = true }
uuid = { version = "1.3", features = ["serde", "v4"] }
x509-parser = { workspace = true }

[dev-dependencies]
env_logger = "0.10"
