[package]
name = "pccs_client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hex = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
urlencoding = "2.1"

[dev-dependencies]
x509-cert = "0.2"
