[package]
name = "sgx_pck_extension"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Parsing of Intel SGX PCK certificate extension"

[dependencies]
asn1-rs = "0.5"
asn1 = "0.15"
x509-parser = { workspace = true }
