on:
  push:
  workflow_call:

name: Rust build, test and lint

jobs:
  check:
    name: Rust CI
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo curl -fsSLo /usr/share/keyrings/intel-sgx-deb.asc https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/intel-sgx-deb.asc] https://download.01.org/intel-sgx/sgx_repo/ubuntu noble main" | sudo tee /etc/apt/sources.list.d/intel-sgx.list
          sudo apt-get update && sudo apt-get install -y tpm2-tools libtss2-dev libtdx-attest=1.26.100.1-noble1 libtdx-attest-dev=1.26.100.1-noble1

      - name: Install Rust toolchain and components
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install cargo-machete
        run: cargo install cargo-machete

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo check
        run: cargo check

      - name: Cargo clippy
        run: cargo clippy -- -D warnings

      - name: Cargo machete (deps checker)
        run: cargo machete

      - name: Cargo test
        run: cargo test --lib -- --nocapture

      - name: Build test binaries
        run: cargo test --tests --no-run

      - name: Upload test binaries
        uses: actions/upload-artifact@v4
        with:
          name: test-binaries
          path: |
            target/debug/deps/aws_integration_tests-*[!.d]
            target/debug/deps/az_integration_tests-*[!.d]
            target/debug/deps/gcp_integration_tests-*[!.d]

      - name: Cargo build
        run: cargo build --release
