on: [push]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.env }}

    strategy:
      matrix:
        include:
          - env: "no-tee"
            docker-opt: "--device /dev/tpmrm0"
          # TODO: enable this when SEV runner is working
          # - env: "sev"
          #   docker-opt: "--device /dev/sev-guest --device /dev/tpmrm0"
          # TODO: enable this when TDX runner is working
          # - env: "tdx"
          #   docker-opt: "--device /dev/tdx_guest --device /dev/tpmrm0"
          - env: "sgx"
            docker-opt: "--device /dev/sgx_enclave --device /dev/sgx_provision"
    container:
      image: ghcr.io/cosmian/intel-sgx:2.25 # We work in a container because we need root access for some tests (get quote for example)
      options: ${{ matrix.docker-opt }} # We need the device to get TPM, TDX or SEV quote
    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y libssl-dev tpm2-tools libtss2-dev libtdx-attest-dev

      - uses: actions/checkout@v2

      - name: Rustup setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: rustup component add rustfmt && rustup component add clippy && cargo install cargo-machete

      - name: Security Audit
        uses: EmbarkStudios/cargo-deny-action@v2

      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Machete (deps checker)
        uses: actions-rs/cargo@v1
        with:
          command: machete

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture # We want to display messages concerning skipped tests
