---
on:
  pull_request:

name: Integration tests on cloud providers

jobs:
  cleanup: # we remove the Github cache to avoid any conflict
    name: Clean Github cache
    uses: Cosmian/reusable_workflows/.github/workflows/cleanup_cache.yml@main
    secrets: inherit

  build-binaries:
    needs: cleanup
    name: Build binaries
    uses: ./.github/workflows/build.yml

  gcp:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu]  # rhel
        techno: [sev]  # tdx
    name: GCP
    needs:
      - build-binaries
    secrets: inherit
    uses: ./.github/workflows/gcp.yml
    with:
      techno: ${{ matrix.techno }}
      distrib: ${{ matrix.distrib }}

  azure:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu]  # rhel
        techno: [sev]  # tdx
    name: Azure
    needs:
      - build-binaries
    secrets: inherit
    uses: ./.github/workflows/azure.yml
    with:
      techno: ${{ matrix.techno }}
      distrib: ${{ matrix.distrib }}
