---
on:
  pull_request:

name: Integration tests on cloud providers

jobs:
  build-binaries:
    name: Build binaries
    uses: ./.github/workflows/build.yml

  gcp:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu]  # rhel
        techno: [sev]  # tdx
    name: GCP
    needs:
      - build-binaries
    secrets:
      GOOGLE_COSMIAN_DEV_CREDENTIALS: ${{ secrets.GOOGLE_COSMIAN_DEV_CREDENTIALS }}
    uses: ./.github/workflows/gcp.yml
    with:
      techno: ${{ matrix.techno }}
      distrib: ${{ matrix.distrib }}

  azure:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu]  # rhel
        techno: [sev]  # tdx
    name: Azure
    needs:
      - build-binaries
    secrets:
      AZURE_CREDS_JSON: ${{ secrets.AZURE_CREDS_JSON }}
    uses: ./.github/workflows/azure.yml
    with:
      techno: ${{ matrix.techno }}
      distrib: ${{ matrix.distrib }}

  aws:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu]  # rhel
        techno: [sev]  # tdx
    name: AWS
    needs:
      - build-binaries
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PACKER_AWS_SSH_PRIVATE_KEY: ${{ secrets.PACKER_AWS_SSH_PRIVATE_KEY }}
    uses: ./.github/workflows/aws.yml
    with:
      techno: ${{ matrix.techno }}
      distrib: ${{ matrix.distrib }}
